version: '3'

services:
  postgres:
    image: 'postgres:16'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=khuja'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_DB=amonatbankVolunteer'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8082:8082